name: smart_sentry
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^5.5.1
  firebase_auth: ^5.3.3
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  firebase_messaging: ^15.1.6
  firebase_storage: ^12.3.7
  flutter:
    sdk: flutter
  geolocator: ^13.0.2
  google_maps: ^8.1.1
  google_maps_flutter: ^2.10.0
  googleapis: ^13.2.0
  googleapis_auth: ^1.6.0
  http: ^1.2.2
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.4
  stacked: ^3.4.3
  stacked_firebase_auth: ^2.21.0
  stacked_services: ^1.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3

flutter:
  uses-material-design: true

